# @author : microfat
# @time   : 04/21/22 10:46:23
# @File   : docker-compose.yml

version: "3.8"
services: 
    jdy_data_test:
        image: jdy_data_test:2.1
        container_name: jdy_data_test_2.1
        build: .
        ports: 
            - 3102:3102
        tty: true
        env_file:
            - .env
        restart: always

    swagger_ui:
        image: swaggerapi/swagger-ui
        container_name: swagger_ui
        volumes:
            - ./:/files
        ports:
            - 18081:8080
        environment:
            - SWAGGER_JSON=/files/webhook.yaml
        restart: always